
export const images = [
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmpa-OPGCHyX-GPQRrwoR289o79lh94R-ERw&s',
    'https://img.freepik.com/free-photo/painting-mountain-lake-with-mountain-background_188544-9126.jpg',
    'https://images8.alphacoders.com/136/thumb-350-1363709.webp',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYL6nIvJP72d-YQO2iUXcwZfh8875iKYUyTg&s',
];

export const productDetail = {
    name: 'L-Glutathione - for Skin Brightening and Antioxidant Support',
    originalPrice: 1498,
    salePrice: 953,
    ratings: 3.7,
    imageOne: 'https://herbalmax.in/cdn/shop/files/1st-image-color-background-l_glutathione_1.png?v=1731665236&width=823',
    imageTwo: 'https://herbalmax.in/cdn/shop/files/710u_e-myWL._SL1500_d5ce55f8-708e-4cf6-b3e6-61d8cb83889a.png?v=1731665232&width=823',
    imageThree: 'https://herbalmax.in/cdn/shop/files/60-l-glutathione-tablet-for-glowing-skin-reduce-pigmentation-for-original-imah3abwqhztgtp3.jpg?v=1731665236&width=823',
    imageFour: 'https://herbalmax.in/cdn/shop/files/71z4kkYfsuL._SL1500_9b73925c-bcca-44a7-892f-2e8119492a22.png?v=1731665232&width=823',
    imageFive: 'https://herbalmax.in/cdn/shop/files/last_6657254ff358b.jpg?v=1731665229&width=823',
    productId: 'sgrehkliulrhtbtr',
    info: 'Vitamin B12 Capsules are designed to support your daily energy levels and mental focus. Each easy-to-swallow capsule provides essential nutrients, including Vitamin B12, which may help you maintain a more vibrant, energetic lifestyle. Simple, effective, and easy to incorporate into your routine.',
};

export const products = [
    {
        name: 'L-Glutathione - for Skin Brightening and Antioxidant Support',
        originalPrice: 1498,
        salePrice: 953,
        ratings: 2,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehkliulrhtbtr',
    },
    {
        name: 'Organic Ashwagandha - Stress Relief and Immunity Booster',
        originalPrice: 1299,
        salePrice: 899,
        ratings: 2.2,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrertrghtbtr',
    },
    {
        name: 'Turmeric Curcumin - Anti-Inflammatory and Joint Support',
        originalPrice: 1599,
        salePrice: 1049,
        ratings: 2.3,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrhtbjyjytr',
    },
    {
        name: 'Apple Cider Vinegar Gummies - Digestive and Weight Support',
        originalPrice: 999,
        salePrice: 699,
        ratings: 2.7,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrhtdfgbbtr',
    },
    {
        name: 'Collagen Peptides - Skin, Hair, and Joint Health',
        originalPrice: 1899,
        salePrice: 1399,
        ratings: 2.8,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrliuythhtbtr',
    },
    {
        name: 'Probiotic Capsules - Gut Health and Digestive Support',
        originalPrice: 1199,
        salePrice: 849,
        ratings: 0,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrgefgdhtbtr',
    },
    {
        name: 'Vitamin D3 + K2 - Bone and Heart Health',
        originalPrice: 1099,
        salePrice: 799,
        ratings: 1,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrhlkyjtbtr',
    },
    {
        name: 'Magnesium Glycinate - Sleep and Muscle Relaxation',
        originalPrice: 1399,
        salePrice: 999,
        ratings: 5,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrytkuykehrhtbtr',
    },
    {
        name: 'Omega-3 Fish Oil - Heart and Brain Health',
        originalPrice: 1599,
        salePrice: 1149,
        ratings: 2.5,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehtryhdgrhtbtr',
    },
    {
        name: 'Herbal Detox Tea - Cleanse and Refresh',
        originalPrice: 799,
        salePrice: 599,
        ratings: 3.9,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrhii6ktbtr',
    },
];
