
export const images = [
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmpa-OPGCHyX-GPQRrwoR289o79lh94R-ERw&s',
    'https://img.freepik.com/free-photo/painting-mountain-lake-with-mountain-background_188544-9126.jpg',
    'https://images8.alphacoders.com/136/thumb-350-1363709.webp',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYL6nIvJP72d-YQO2iUXcwZfh8875iKYUyTg&s',
];

export const products = [
    {
        name: 'L-Glutathione - for Skin Brightening and Antioxidant Support',
        originalPrice: 1498,
        salePrice: 953,
        ratings: 2,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehkliulrhtbtr',
    },
    {
        name: 'Organic Ashwagandha - Stress Relief and Immunity Booster',
        originalPrice: 1299,
        salePrice: 899,
        ratings: 2.2,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrertrghtbtr',
    },
    {
        name: 'Turmeric Curcumin - Anti-Inflammatory and Joint Support',
        originalPrice: 1599,
        salePrice: 1049,
        ratings: 2.3,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrhtbjyjytr',
    },
    {
        name: 'Apple Cider Vinegar Gummies - Digestive and Weight Support',
        originalPrice: 999,
        salePrice: 699,
        ratings: 2.7,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrhtdfgbbtr',
    },
    {
        name: 'Collagen Peptides - Skin, Hair, and Joint Health',
        originalPrice: 1899,
        salePrice: 1399,
        ratings: 2.8,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrliuythhtbtr',
    },
    {
        name: 'Probiotic Capsules - Gut Health and Digestive Support',
        originalPrice: 1199,
        salePrice: 849,
        ratings: 0,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrgefgdhtbtr',
    },
    {
        name: 'Vitamin D3 + K2 - Bone and Heart Health',
        originalPrice: 1099,
        salePrice: 799,
        ratings: 1,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrhlkyjtbtr',
    },
    {
        name: 'Magnesium Glycinate - Sleep and Muscle Relaxation',
        originalPrice: 1399,
        salePrice: 999,
        ratings: 5,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrytkuykehrhtbtr',
    },
    {
        name: 'Omega-3 Fish Oil - Heart and Brain Health',
        originalPrice: 1599,
        salePrice: 1149,
        ratings: 2.5,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehtryhdgrhtbtr',
    },
    {
        name: 'Herbal Detox Tea - Cleanse and Refresh',
        originalPrice: 799,
        salePrice: 599,
        ratings: 3.9,
        image: 'https://c4.wallpaperflare.com/wallpaper/410/867/750/vector-forest-sunset-forest-sunset-forest-wallpaper-thumb.jpg',
        productId: 'sgrehrhii6ktbtr',
    },
];
